export const KPI_REQUEST = 'KPI_REQUEST';
export const KPI_SUCCESS = 'KPI_SUCCESS';
export const KPI_ADD_SUCCESS = 'KPI_ADD_SUCCESS';
export const KPI_ERROR = 'KPI_ERROR';
export const DISMISS_KPI_ERROR = 'DISMISS_KPI_ERROR';
export const POST_KPI_REQUEST = 'POST_KPI_REQUEST';
export const PUT_KPI_REQUEST = 'PUT_KPI_REQUEST';