export const GET_STYLES_REQUEST = 'GET_STYLES_REQUEST';
export const GET_STYLES_SUCCESS = 'GET_STYLES_SUCCESS';
export const GET_KPI_STYLES_SUCCESS = 'GET_KPI_STYLES_SUCCESS';
export const GET_STYLES_ERROR = 'GET_STYLES_ERROR';
export const DISMISS_STYLES_ERROR = 'DISMISS_STYLES_ERROR';
export const POST_STYLES_REQUEST = 'POST_STYLES_REQUEST';